cgit logo	index : support/ansible.git	

awx
 
GIT_ansible	Mr. Gerrit
summaryrefslogtreecommitdiffstats	

log msg
 
 
path: root/playbooks/awx_send_notification.yml
blob: dc38e1866147e219345785b70c11d157265c9c94 (plain)
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
- name: Send IUN notification
  hosts: localhost
  gather_facts: no

  vars:

  tasks:
    - name: Check if notification should be skipped
      fail:
        msg: "skip_notification=1, skipping"
      when: skip_notification | default(0) == 1

    - name: Check if 'notification' variable is defined and not empty
      fail:
        msg: "'notification' variable is not defined or empty"
      when: notification is undefined or notification | trim == ""

    - name: Check if 'ticket' variable is defined and not empty
      fail:
        msg: "'ticket' variable is not defined or empty"
      when: ticket is undefined or ticket | trim == ""

    - name: Set API target
      set_fact:
        api_target: "{{ 'RT' if ticket is match('^TT[0-9]{1,9}$') else 'YT' if ticket is match('^CSUP-[0-9]+$') else 'Unknown' }}"

    - name: Set RT ticket
      set_fact:
        rt_ticket: "{{ ticket | regex_replace('^TT', '') }}"
      when: api_target == 'RT'

    - name: Send reply to the ticket in RT
      uri:
        url: "{{ rt_url }}/REST/1.0/ticket/{{ rt_ticket }}/comment"
        method: POST
        validate_certs: no
        body_format: form-urlencoded
        body:
          user: "{{ rt_login }}"
          pass: "{{ rt_password }}"
          content: "id: {{ rt_ticket }}\nAction: correspond\nText: {{ notification }}"
        headers:
          Content-Type: "application/x-www-form-urlencoded"
      register: response
      when: api_target == 'RT'

    - name: Set status of RT ticket to 'open'
      uri:
        url: "{{ rt_url }}/REST/1.0/ticket/{{ rt_ticket }}/edit"
        method: POST
        validate_certs: no
        body_format: form-urlencoded
        body:
          user: "{{ rt_login }}"
          pass: "{{ rt_password }}"
          content: "id: {{ rt_ticket }}\nStatus: open"
        headers:
          Content-Type: "application/x-www-form-urlencoded"
      when: api_target == 'RT'

    - name: Check response from RT
      debug:
        var: response
      when: api_target == 'RT'

    - name: Add a reply to the ticket in YT
      debug:
        msg: "YouTrack notifications are not implemented yet"
      when: api_target == 'YT'

generated by cgit (git 2.34.1) at 2024-02-02 18:10:27 +0000
