- name: Send notification to ticket
  hosts: localhost
  gather_facts: no

  vars:
    rt_url: "https://rt4.int.portaone.com"
    rt_login_url: "{{ rt_url }}"
    rt_comment_url: "{{ rt_url }}/REST/1.0/ticket/{{ ticket_id }}/comment"
    rt_username: "{{ rt_login }}"
    rt_password: "{{ rt_password }}"
    rt_content: "id: {{ ticket_id }} \nAction: correspond \nText: {{ notification | urlencode }}"

  tasks:
    - name: Check if 'notification' variable is defined and not empty
      fail:
        msg: "'notification' variable is not defined or empty"
      when: notification is undefined or notification | trim == ""

    - name: Check if 'ticket_id' variable is defined and not empty
      fail:
        msg: "'ticket_id' variable is not defined or empty"
      when: ticket_id is undefined or ticket_id | trim == ""

    - name: Login to RT
      uri:
        url: "{{ rt_login_url }}"
        method: POST
        body_format: form-urlencoded
        body:
          username: "{{ rt_username }}"
          password: "{{ rt_password }}"
        headers:
          Content-Type: "application/x-www-form-urlencoded"
        validate_certs: no  
        return_content: yes
      register: login_response

    - name: Debug login response
      debug:
        var: login_response

    - name: Add a reply to the ticket in RT
      uri:
        url: "{{ rt_comment_url }}"
        method: POST
        body_format: form-urlencoded
        body:
          content: "{{rt_content}}" 
        headers:
          Content-Type: "form-data"
          Referer: "{{ rt_url }}"
          Cookie: "{{ login_response.cookies_string }}"
        validate_certs: no  
      register: comment_response

    - name: Debug comment response
      debug:
        var: comment_response
