---
- name: Post Comment to RT Ticket
  hosts: localhost
  gather_facts: no

  vars:
    rt_username: "{{ rt_login }}"
    rt_password: "{{ rt_password }}"

  tasks:
    - name: Check if 'ticket_id' variable is defined and not empty
      fail:
        msg: "'ticket_id' variable is not defined or empty"
      when: ticket_id is undefined or ticket_id | trim == ""

    - name: Check if 'comment_text' variable is defined and not empty
      fail:
        msg: "'comment_text' variable is not defined or empty"
      when: comment_text is undefined or comment_text | trim == ""

    - name: Generate the multipart/form-data payload
      set_fact:
        multipart_payload:
          QuoteTransaction: 64032882
          DefaultStatus: open
          Action: Respond
          SubmitTicket: 1
          Token: 3e3053152ec22f74b56a370d9be41699
          UpdateStartedAt: "2023-11-27 01:10:56"
          old_Priority: 20
          id: "{{ ticket_id }}"
          UpdateType: response
          Status: ""
          Owner: ""
          Priority: 20
          UpdateSubject: "AWX Test TT"
          SelectTemplate: ""
          794720-RefersTo: ""
          Articles_Content: ""
          Articles-Include-Article-Named: ""
          UpdateContent: "On 2023-11-17 06:33:21, Oleksii Bondar wrote:\n> {{ comment_text }}"
          # Replace {{ comment_text }} with the actual comment text

    - name: Post comment to RT ticket
      uri:
        url: "https://your-rt-instance.example.com/Ticket/Update.html?id={{ ticket_id }}&Action=Respond"
        method: POST
        user: "{{ rt_username }}"
        password: "{{ rt_password }}"
        headers:
          Content-Type: "multipart/form-data"
        body: "{{ multipart_payload }}"
        status_code: 200
        return_content: yes
      register: response

    - name: Debug API Response
      debug:
        var: response.content

    # You can add additional tasks or error handling as needed
