- name: Reply to RT Ticket via Email
  hosts: localhost
  gather_facts: no

  vars:
    rt_email: "borland@sadasdas.com.ua"  # Replace with your RT email address
    ticket_id: "{{ ticket_id }}"
    notification: "{{ notification }}"
    smtp_server: "asdasdas.com"
    smtp_user: "asdadas"
    smtp_password: "zzz"
    smtp_port: 587

  tasks:
    - name: Check if 'notification' variable is defined and not empty
      fail:
        msg: "'notification' variable is not defined or empty"
      when: notification is undefined or notification | trim == ""

    - name: Check if 'ticket_id' variable is defined and not empty
      fail:
        msg: "'ticket_id' variable is not defined or empty"
      when: ticket_id is undefined or ticket_id | trim == ""

    - name: Send email to RT
      mail:
        host: "{{ smtp_server }}"
        port: "{{ smtp_port }}"
        username: "{{ smtp_user }}"
        password: "{{ smtp_password }}"
        to: "{{ rt_email }}"
        subject: "[Ticket #{{ ticket_id }}] Update"
        body: "{{ notification }}"
        secure: starttls
      delegate_to: localhost
