- name: runnn
  hosts: all
  gather_facts: no
  tasks:
    - name: run1
      shell:
        cmd: "{{ command1 }}"
      register: command1result

    - name: transfer data to pass down to the next Job template
      set_stats:
        data:
          output1: "{{ command1result.stdout }}" 
