- name: runnn
  hosts: all
  gather_facts: no
  tasks:
    - name: zapusk
      shell:
        cmd: "{{ command1 }}"
      register: result1
      
    - name: next
      shell:
        cmd: "{{ command2 }}"
      register: result2

    - name: transfer data to pass down to the next Job template
      set_stats:
        data:
          output1: "{{ result1.stdout }}" 
