- hosts: all
  tasks:

    - name: send email from variables
      shell: 
       cmd:  echo "{{ output1 }} {{ email_text1 }} \n {{ output2 }} {{ email_text2 }}"  | mail -s "{{ email_subject }}" {{ email_recipient }}
