- name: run commands
  hosts: all
  gather_facts: no
  tasks:
    - name: run1
      shell:
        cmd: "{{ command_1 }}"
      register: command1_result

    - name: run2
      shell:
        cmd: "{{ command_2 }}"
      register: command2_result
      
    - name: transfer data to pass down to the next Job template
      set_stats:
        data:
          output1: "{{ command1_result.stdout }}" 
          output2: "{{ command2_result.stdout }}"
