- hosts: all
  tasks:
      - name: send email with variable
        shell: 
          cmd:  echo "{{ tables_list }} calls have been produced for the previous day" | mail -s "Ansible Results" bondar.aleks.v@gmail.com
